### ISSUE TITLE
I get jade warning when running spark-viz

### ISSUE THREAD

**Issue by phileas-condemine** [SoatGroup/spark-redis-nodejs#1]
The message warning is "You should not have jade tags with multiple attributes."

**Comment by mccstan** [comment]
Have you get the app  up and running ?
If you have donne npm install  before running, you could ignore the warnings : The is available on localhost:3000 !

**Comment by phileas-condemine** [comment]
Yes the app is running, but in the app I can't see the data I publish to spark-metrics, so I'm looking for the reason.

**Comment by mccstan** [comment]
OK !
Be sure your have started a redis instance : redis-server
![capture du 2017-05-19 15-10-15](https://cloud.githubusercontent.com/assets/16156036/26249260/206ca3ae-3ca6-11e7-88af-5ab4031d5c7f.png)

Then be sure the streaming app is runnning and the resuslts are displyed on the terminal :
![capture du 2017-05-19 15-12-54]
(https://cloud.githubusercontent.com/assets/16156036/26249303/475b5fbe-3ca6-11e7-8674-fb24d608e03a.png)

The Dashbord is an Angular based app with CDN dependancies (looking for some from internet) : So be sure to connect to the internet(If you are using the provided VM, just connect to the ethernet)

The dahsboard will look like 👍 
![capture du 2017-05-19 15-14-57](https://cloud.githubusercontent.com/assets/16156036/26249405/b158467a-3ca6-11e7-8f53-d12c65545402.png)

**Comment by mccstan** [comment]
OK
