### ISSUE TITLE
App spark-viz running OK but flow published to spark-metrics not displayed in the app

### ISSUE THREAD

**Issue by phileas-condemine** [SoatGroup/spark-redis-nodejs#2]
I think this is not an actual issue but rather some misunderstanding of how to use the app.
In first CLI I type redis-server
In second CLI I type redis-CLI then SUBSCRIBE spark-metrics
In third CLI I type redis-CLI then PUBLISH spark-metrics "hello world!"
In fourth CLI I type node server and open localhost:3000 in my browser.
Whenever I publish new data through 3rd CLI I see it through the subscribed one (2nd CLI) but I see nothing in the app (localhost:3000).
Is it spark-metrics I should publish to ?

**Comment by mccstan** [comment]
Ok I see what you aim to achive : 
You are not using the right topic name.
The topics available are : 
stream-transitions
summary-metrics
detail-metrics
raw-messages

You could SUBSCRIBE to these channels and see the data structures and then publish following these ones !
Tell me if this is what you want to achieve !

**Comment by phileas-condemine** [comment]
Yes ! I see the raw-messages in the app. It's clear, thx.

**Comment by mccstan** [comment]
You're welcome ! 😄
